### ISSUE TITLE
migrations table optional name

### ISSUE THREAD

**Issue by adiweiss** [lopezator/migrator#13]
a suggestion to allow to set the migrations version table name, something that can be useful if there are several versions to manage (like in case there's a library using migrator)

**Comment by lopezator** [comment]
Good suggestion.

Maybe we should turn the` tableName` const into a car and export it so you could set it from outside or use it a setter method somehow?

For example:

https://github.com/pressly/goose/blob/master/version.go

**Comment by adiweiss** [comment]
pr: https://github.com/lopezator/migrator/pull/14

**Comment by lopezator** [comment]
Thank you for your work @adiweiss !! I'll review this next week, as I'm off for this week.

**Comment by lopezator** [comment]
Closed via https://github.com/lopezator/migrator/pull/18
