### ISSUE TITLE
Make Name be SQL safe before inserting

### ISSUE THREAD

**Issue by glerchundi** [lopezator/migrator#23]
When trying to use a `Name` with SQL-reserved characters like **'** it dramatically fails:

```
migrator: error while running migrations: error updating migration versions: pq: syntax error at or near \"myvalue\"
```

 For example:

```
&migrator.MigrationNoTx{
	Name: "table: refactor 'myvalue/*' to 'prefixed-myvalue/*'",
	Func: func(db *sql.DB) error {
		[...]
	},
}
```

It should be relatively easy to solve the issue by escaping the `Name` before performing the insert.

**Comment by lopezator** [comment]
Having into account that `migration.Name` is always a dev-provided and not user-provided value, the validity of the input is supposed.

In addition to that, the escaping is dependant of the underlying db engine used:

e.g. escape a single quote is:

* `''` in PostgreSQL
* `\'` in MySQL

As migrator wants abstract the db used by the use of `database\sql`, and avoid cluttering this with dependencies and complex logic, I'll leave the escaping/sanitizing of the input to the user of migrator.

Adding a note to warn users about this would be great though.

Thanks for raising this!

**Comment by glerchundi** [comment]
Makes sense, thanks!
