### ISSUE TITLE
example in readme doesn't compile

### ISSUE THREAD

**Issue by deogracia** [lopezator/migrator#26]
Hi, i'm trying to run the quick start example: it doesn't compile.

### My env:

* go version: `go version go1.13.3 linux/amd64`

### How to reproduce

* `docker run -it --rm golang:1.13.3-stretch bash`
* `mkdir -p /go/src/bob && cd $_`
* copy and paste the quick start example in main.go
* run go build main.go

### expected results
* no error

### actual results

```
# bob                                               
./main.go:12:4: assignment mismatch: 1 variable but migrator.New returns 2 values
./main.go:13:3: undefined: Migrations
```

**Comment by deogracia** [comment]
The "assignment mismatch" error can be resolved with this

```diff
diff --git a/main.go b/main.go
index db654d7..7f694fd 100644
--- a/main.go
+++ b/main.go
@@ -9,7 +9,7 @@ import (
 )

 func main() {
-       m := migrator.New(
+       m, err := migrator.New(
                Migrations(
                        &migrator.Migration{
                                Name: "Create table foo",
@@ -22,6 +22,9 @@ func main() {
                        },
                ),
        )
+       if err != nil {
+               log.Fatal(err)
+       }

        // Migrate up
```

But I can't see how to fix the "undefined: Migrations" error

**Comment by lopezator** [comment]
Hello @deogracia thanks a lot for using migrator and for your bug report!

You are correct, example on README.md was wrong, I've updated it, please let me know if this works for you so we can close the issue.

**Comment by deogracia** [comment]
Thanks @lopezator ! Everything compiles now :D

**Comment by lopezator** [comment]
You're welcome! Let me know if you have any doubts or run into any problem.
