### ISSUE TITLE
config or opt-out for stdout logging

### ISSUE THREAD

**Issue by adamdecaf** [lopezator/migrator#30]
Hey @lopezator! Thanks for this quick library.

I run these migrations a lot in tests and the `fmt.Printf` calls fill test results on errors (or from setting `-v`). I'd like an option to disable/opt-out of those calls (which I'll set in tests).

What about `func (m *Migrator) DisableLogging()` (or `SetLogger`) call? 

Thoughts?

**Comment by lopezator** [comment]
Hello @adamdecaf first of all, thanks for using migrator!

I think this is a great idea. I like to see migrations output on my CI runs, but I agree that having an option to enable/disable it would be useful for users.

Let me think a bit about this and I will get back to you shortly.

**Comment by lopezator** [comment]
I just uploaded a proposal in https://github.com/lopezator/migrator/pull/31 please take a look when you could. I would appreciate feedback.

I want something:

- Small.
- Without any external dependency.
- Extensible.

Let me know if this could work for you.

**Comment by lopezator** [comment]
Closed by https://github.com/lopezator/migrator/pull/31

**Comment by lopezator** [comment]
v0.3.0 released so you can pin to the new version @adamdecaf ;)
