### ISSUE TITLE
Export the migration interface to allow dynamically building the migration list

### ISSUE THREAD

**Issue by grimmy** [lopezator/migrator#8]
I'm trying to use esc to load my migrations dynamically, but since I can't create the right type for a list I can't make it work.

Long story short, the following code grabs all the files from `esc` sorts them by name (they're named `001-foo.sql`, `002-bar.sql`, etc) and then tries to add them to migrator.

```golang
    nMigrations := len(_escDirs["."])
    names := make([]string, nMigrations)
    sort.Strings(names)

    migrations := make([]*migrator.Migration, nMigrations)
    for i, name := range names {
        data, err := _escStatic.prepare(name)
        if err != nil {
            return err
        }

        migrations[i] = &migrator.Migration{
            Name: name,
            Func: func(tx *sql.Tx) error {
                _, err := tx.Exec(string(data.data))

                return err
            },
        }
    }

    migrator := migrator.New(migrations...)

    return migrator.Migrate(db)
```

But due to `New` only taking an interface I can't create a slice of I'm SOL...

So long story short, would you consider a merging a PR that is exposed to make this possible?

**Comment by lopezator** [comment]
Hello @grimmy first of all, thank you for using migrator and for providing valuable feedback!

Of course, I am completely open to PR's, I will take a look into this also in parallel, so we'll can find a solution together.

Thanks.

**Comment by lopezator** [comment]
Btw, I use migrator like this, so I din't fall on that usecase:

`migrator.go`:

```
// Migrate runs the defined migrations
func Migrate(db *sql.DB) error {
	// Create migrator
	migrator := migratorpkg.New(
		migration00000(),
		migration00001(),
	)

	// Migrate
	if err := migrator.Migrate(db); err != nil {
		return err
	}

	return nil
}

func getSQL(id string) string {
	seed, err := _escFSString(false, fmt.Sprintf("/internal/migration/sql/%s.sql", id))
	if err != nil {
		panic(err)
	}
	return seed
}
```

```00000.go, 00001.go, etc...```

```
func migration00000() *migrator.Migration {
	return &migrator.Migration{
		Name: "*: initial migration, create all tables",
		Func: func(tx *sql.Tx) error {
			if _, err := tx.Exec(getSQL("00000")); err != nil {
				return err
			}
			return nil
		},
	}
}
```
So every migration is composed by its own file and just a new line on `migrator.go`.

**Comment by lopezator** [comment]
Via https://github.com/lopezator/migrator/pull/16

You could now accomplish this, just by changing the following line from your original implementation:

```migrations := make([]interface{}, nMigrations)```

Let me know if this works for you @grimmy if not, feel free to reopen this issue & comment.
